print("what is your name?")
#variable is a container ,which can store data for us in the memory (string,integer,float,boo)
name =input()
print("what is your age ?")
age = input()
print(type(age))
print("what is your bank balance?")
balance = float(input())

print ("welcome {}. you are said to be {}years old .your bank balance is:.2f}.".format(name,age,balance))